apiVersion: batch/v1
kind: Job
metadata:
  name: ntap-dsutil
  namespace: default # Replace with desired namespace
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: ntap-dsutil
        image: python:3
        command:
        - "/bin/bash"
        - "-c"
        - "python3 -m pip install ipython kubernetes pandas tabulate && \
           git clone https://github.com/NetApp/netapp-data-science-toolkit && \
           mv /netapp-data-science-toolkit/Kubernetes/ntap_dsutil_k8s.py / && \
           /ntap_dsutil_k8s.py list jupyterlabs" # Replace with desired command
        imagePullPolicy: IfNotPresent
      serviceAccountName: ntap-dsutil
      restartPolicy: Never
