---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ntap-dsutil
  namespace: default # Replace with desired namespace
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ntap-dsutil
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims", "persistentvolumeclaims/status", "services"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshots", "volumesnapshots/status", "volumesnapshotcontents", "volumesnapshotcontents/status"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: ["apps", "extensions"]
  resources: ["deployments", "deployments/scale", "deployments/status"]
  verbs: ["get", "list", "create", "delete", "patch", "update"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ntap-dsutil
subjects:
- kind: ServiceAccount
  name: ntap-dsutil
  namespace: default # Replace with desired namespace
roleRef:
  kind: ClusterRole
  name: ntap-dsutil
  apiGroup: rbac.authorization.k8s.io
