kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dataset-vol
  namespace: kubeflow
spec:
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
     storage: 20Gi
  storageClassName: storage-class-nas
