
apiVersion: storage.k8s.io/v1

kind: StorageClass

metadata:

 name: ontap-ai-flexgroups-retain-iface2

provisioner: netapp.io/trident

parameters:

 backendType: "ontap-nas-flexgroup"

 storagePools: "ontap-ai-flexgroups-iface2:.*"

reclaimPolicy: Retain

