apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: delete-snapshot-2-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.2, pipelines.kubeflow.org/pipeline_compilation_time: '2021-06-02T02:13:18.720885',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Template for deleting
      a snapshot in Kubernetes", "inputs": [{"default": "snap1", "name": "volume_snapshot_name",
      "optional": true, "type": "String"}], "name": "Delete Snapshot"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.2}
spec:
  entrypoint: delete-snapshot-2
  templates:
  - name: delete-snapshot
    container:
      args: ['            python3 -m pip install ipython kubernetes pandas tabulate
          &&             git clone https://github.com/NetApp/netapp-data-science-toolkit
          &&             mv /netapp-data-science-toolkit/Kubernetes/ntap_dsutil_k8s.py
          / &&             echo ''{{inputs.parameters.volume_snapshot_name}}'' > /deleted_volume_snapshot_name.txt
          &&             /ntap_dsutil_k8s.py delete volume-snapshot --snapshot-name={{inputs.parameters.volume_snapshot_name}}
          --namespace={{workflow.namespace}} --force']
      command: [/bin/bash, -c]
      image: python:3
    inputs:
      parameters:
      - {name: volume_snapshot_name}
    outputs:
      artifacts:
      - {name: delete-snapshot-deleted_volume_snapshot_name, path: /deleted_volume_snapshot_name.txt}
    metadata:
      labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.2, pipelines.kubeflow.org/pipeline-sdk-type: kfp}
  - name: delete-snapshot-2
    inputs:
      parameters:
      - {name: volume_snapshot_name}
    dag:
      tasks:
      - name: delete-snapshot
        template: delete-snapshot
        arguments:
          parameters:
          - {name: volume_snapshot_name, value: '{{inputs.parameters.volume_snapshot_name}}'}
  arguments:
    parameters:
    - {name: volume_snapshot_name, value: snap1}
  serviceAccountName: pipeline-runner
