apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: delete-volume-2-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.2, pipelines.kubeflow.org/pipeline_compilation_time: '2021-06-02T02:13:26.411414',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Template for deleting
      a volume in Kubernetes", "inputs": [{"default": "datavol", "name": "pvc_name",
      "optional": true, "type": "String"}], "name": "Delete volume"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.2}
spec:
  entrypoint: delete-volume-2
  templates:
  - name: delete-volume
    container:
      args: ['            python3 -m pip install ipython kubernetes pandas tabulate
          &&             git clone https://github.com/NetApp/netapp-data-science-toolkit
          &&             mv /netapp-data-science-toolkit/Kubernetes/ntap_dsutil_k8s.py
          / &&             echo ''{{inputs.parameters.pvc_name}}'' > /deleted_pvc_name.txt
          &&             /ntap_dsutil_k8s.py delete volume --pvc-name={{inputs.parameters.pvc_name}}
          --namespace={{workflow.namespace}} --force']
      command: [/bin/bash, -c]
      image: python:3
    inputs:
      parameters:
      - {name: pvc_name}
    outputs:
      artifacts:
      - {name: delete-volume-deleted_pvc_name, path: /deleted_pvc_name.txt}
    metadata:
      labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.2, pipelines.kubeflow.org/pipeline-sdk-type: kfp}
  - name: delete-volume-2
    inputs:
      parameters:
      - {name: pvc_name}
    dag:
      tasks:
      - name: delete-volume
        template: delete-volume
        arguments:
          parameters:
          - {name: pvc_name, value: '{{inputs.parameters.pvc_name}}'}
  arguments:
    parameters:
    - {name: pvc_name, value: datavol}
  serviceAccountName: pipeline-runner
